# Generated by Django 5.0.2 on 2024-06-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experiance',
            new_name='experience',
        ),
    ]
