# Generated by Django 5.0.2 on 2024-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='title',
            field=models.CharField(default='Job Application', max_length=100),
        ),
    ]
